name       : haskell-pipes-concurrency
version    : 2.0.10
release    : 2
source     :
    - https://hackage.haskell.org/package/pipes-concurrency-2.0.10/pipes-concurrency-2.0.10.tar.gz : 4675721dbff765ac69dd570d90dc816b4b625e39997d4c2640567a544fe636e3
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides light-weight concurrency primitives for pipes
description: |
    This library provides light-weight concurrency primitives for pipes
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-contravariant
    - haskell-pipes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
