name       : haskell-pipes-concurrency
version    : 2.0.12
release    : 3
source     :
    - https://hackage.haskell.org/package/pipes-concurrency-2.0.12/pipes-concurrency-2.0.12.tar.gz : 4343c67710e2fcd8987c537389773358150559bf06e86d96b1097c15ae81589d
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides light-weight concurrency primitives for pipes
description: |
    This library provides light-weight concurrency primitives for pipes
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-contravariant-devel
    - haskell-pipes-devel
    - haskell-semigroups-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-contravariant-devel
        - haskell-pipes-devel
        - haskell-semigroups-devel
networking : yes
setup      : |
    sed -i "s|< 0.19|< 0.20|g" pipes-concurrency.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
